services:
  - type: web
    name: cbir-django
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      startCommand: gunicorn cbir_project.wsgi
    plan: free
